name: "transactions_dbt"
version: "1.0.0"
config-version: 2

profile: "transactions_profile"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ["dbt_utils", "dbt"]

models:
  transactions_dbt:
    +materialized: table
    staging:
      +schema: staging
    marts:
      +schema: marts

seeds:
  +schema: raw
  transactions_dbt:
    transactions:
      +quote_columns: false
