transactions_profile:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: analytics
      database: analytics
      host: "127.0.0.1"
      port: 8123
      user: "dbt"
      password: "dbt"
      secure: false
      verify: false
      threads: 4
      connect_timeout: 10
      retries: 2
